# Generated by Django 5.2.5 on 2025-08-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_options_alter_post_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="post",
            managers=[],
        ),
    ]
