# Generated by Django 5.2.5 on 2025-08-11 15:33

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_alter_comment_post"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="comment",
            managers=[
                ("active_comments", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
