# Generated by Django 5.2.5 on 2025-08-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_alter_comment_managers_comment_date_updated_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="comment",
            managers=[],
        ),
    ]
